import { chromium } from "@playwright/test";
import { fileURLToPath } from "node:url";
const pdf = fileURLToPath(new URL("./e2e/assets/sample.pdf", import.meta.url));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1000, height: 1000 }, deviceScaleFactor: 2 });
let n=0; p.on("console", m=>{ if(m.text().startsWith("DBG drawText")) n++; });
await p.goto("http://localhost:4173/");
await p.locator('input[type="file"]').first().setInputFiles(pdf);
await p.waitForSelector("canvas.preview__canvas");
await p.waitForTimeout(1500);
console.log("drawText calls:", n);
await p.locator("canvas.preview__canvas").screenshot({ path: "_shot3.png" });
await b.close();
